### ISSUE TITLE
[Bug] Viewing information on network tables

### ISSUE THREAD

**Issue by PatribotsProgramming** [Mechanical-Advantage/URCL#4] opened 2024-02-19 21:13 UTC
Using `URCL.start(*Insert example hashmap here*)` there are only three entries that appear in the network tables viewer. I remember URCL v2024.0.1 had each motor as its own entry, and I can see that the code hasn't changed _that_ much from v0.1 to v1.0.
After looking through the code, I think that the culprit would be using `"\"` rather than `"/"` [here](https://github.com/Mechanical-Advantage/URCL/commit/d5e89952a2956e3918312d32f2f91cbb54ae3ccc#diff-3f809b5b93ad8dc9d15fa44759cb7dbcaf2886c928fb840772a6fd5f14f630dcR153-R162) in the diff for the commit. Just spitting thoughts here, what I am seeing inside of AdvantageScope is attached below. I am running AdvantageScope `v3.2.0`.
Sorry if I am missing something obvious!
![URCL logging example tree](https://github.com/Mechanical-Advantage/URCL/assets/97857553/be40b8ef-a919-4214-808c-092cb434f7c6)

**Comment by GalexY727** [comment] 2024-02-19 21:17
I forgot to mention that the fields are most definitely updating, I can see "movement" in the table view of the bytes byte-ing.

**Comment by jwbonner** [comment] 2024-02-19 21:23
Can you upload a log file where you're seeing the issue?

**Comment by PatribotsProgramming** [comment] 2024-02-19 23:21
Well-- I went to open the log I was about to upload, and voila! The motors are there! How can I send them to network tables when I preview live data? I can currently only see the information after I download and reopen the log.

**Comment by jwbonner** [comment] 2024-02-19 23:22
Could you try changing the "Live Mode" in the AdvantageScope preferences to "Logging"? It's possible that there's an edge case with the "Low Bandwidth" mode.

**Comment by GalexY727** [comment] 2024-02-19 23:35
That worked! I would like to clarify that we don't use AdvntageKit, for the record. Sorry for not clarifying that earlier.

**Comment by jwbonner** [comment] 2024-02-19 23:37
No problem. That's still not the intended behavior but I'll document it for now and make sure that's fixed for the next version.

**Comment by jwbonner** [comment] 2024-09-21 00:06
Closed by https://github.com/Mechanical-Advantage/AdvantageScope/pull/192

**Closed as completed by jwbonner** 2024-09-21 00:06 UTC
